"""Postgres-backed, drop-in replacement for the NocoDB REST client.

Way 1 hard cutover: the pipeline's data layer moves from NocoDB's HTTP API to
direct SQL against the dedicated `pricesync-postgres` (the same instance that
holds the procrastinate queue). This class mirrors the exact `nocodb.NocoDB`
interface — `list_tables` / `list_all` / `bulk_create` / `bulk_update` /
`bulk_delete` / `create_table` / `create_column` / `list_columns` — so every
caller keeps working with `table_ids(base)[title]` → id → data methods unchanged.

Table identity is BASE-PREFIXED (`mc_Products`, `zah_Products`) because both
NocoDB bases have a `Products` and a `PriceHistory` table. `list_tables(base)`
returns the prefixed names as ids, so the title→id maps stay correct.

Values are coerced on read to match what NocoDB returned (whole floats → int, so
id columns stay ints for dict-keying; Decimal → number) — keeping it a true
drop-in for code that does `live.get(r["McWcId"])` etc.
"""

from __future__ import annotations

import datetime as _dt
import os
from decimal import Decimal

import psycopg
from psycopg.rows import dict_row

CHUNK = 500

# Stable NocoDB base-id → PG table prefix. Hardcoded (the bases don't change) but
# env-overridable. Both apps (dashboard + scraper) pass these same base-id strings.
_PREFIX = {
    os.getenv("MC_BASE_ID", "pr1f191l3pjr0d4"): "mc",
    os.getenv("ZAH_BASE_ID", "pl1dzby064y3coj"): "zah",
}


class NocoDBError(RuntimeError):
    pass


def _dsn() -> str:
    return os.getenv("PG_DSN") or os.getenv("QUEUE_DSN") or ""


def prefix_for(base_id: str) -> str:
    if base_id in ("mc", "zah"):
        return base_id
    p = _PREFIX.get(base_id)
    if p:
        return p
    raise NocoDBError(f"unknown base id {base_id!r} — add it to pgdb._PREFIX")


# uidt → PG column type
def pg_type(uidt: str) -> str:
    if uidt == "ID":
        return "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    if uidt in ("Number", "Decimal", "Currency", "Percent", "Rating", "Duration"):
        return "DOUBLE PRECISION"
    if uidt == "Checkbox":
        return "BOOLEAN"
    return "TEXT"


def _coerce(v):
    """Make a SQL value look like NocoDB's JSON: whole numbers → int (so id
    columns key dicts correctly), Decimal → number, datetimes → ISO string."""
    if isinstance(v, bool) or v is None:
        return v
    if isinstance(v, Decimal):
        v = float(v)
    if isinstance(v, float):
        return int(v) if v.is_integer() else v
    if isinstance(v, (_dt.datetime, _dt.date)):
        return v.isoformat()
    return v


def _q(ident: str) -> str:
    """Quote an identifier (table/column) — names are CamelCase, must be quoted."""
    return '"' + ident.replace('"', '""') + '"'


class PgDB:
    def __init__(self, dsn: str | None = None):
        self._conn = psycopg.connect(dsn or _dsn(), autocommit=True, row_factory=dict_row)

    def __enter__(self) -> "PgDB":
        return self

    def __exit__(self, *exc) -> None:
        try:
            self._conn.close()
        except Exception:                                      # noqa: BLE001
            pass

    # ── meta ──────────────────────────────────────────────────────────────────
    def list_tables(self, base_id: str) -> list[dict]:
        prefix = prefix_for(base_id)
        with self._conn.cursor() as cur:
            cur.execute(
                "SELECT table_name FROM information_schema.tables "
                "WHERE table_schema='public' AND table_name LIKE %s ORDER BY table_name",
                (prefix + "\\_%",))
            rows = cur.fetchall()
        out = []
        for r in rows:
            name = r["table_name"]
            out.append({"id": name, "title": name[len(prefix) + 1:]})
        return out

    def list_columns(self, table_id: str) -> list[str]:
        with self._conn.cursor() as cur:
            cur.execute(
                "SELECT column_name FROM information_schema.columns "
                "WHERE table_schema='public' AND table_name=%s ORDER BY ordinal_position",
                (table_id,))
            return [r["column_name"] for r in cur.fetchall()]

    def create_table(self, base_id: str, title: str, columns: list[tuple[str, str]]) -> str:
        name = f"{prefix_for(base_id)}_{title}"
        defs = []
        has_id = any(n == "Id" or u == "ID" for n, u in columns)
        if not has_id:
            defs.append(f'{_q("Id")} {pg_type("ID")}')
        for n, u in columns:
            defs.append(f"{_q(n)} {pg_type(u)}")
        with self._conn.cursor() as cur:
            cur.execute(f'CREATE TABLE IF NOT EXISTS {_q(name)} ({", ".join(defs)})')
        return name

    def create_column(self, table_id: str, name: str, uidt: str) -> None:
        with self._conn.cursor() as cur:
            cur.execute(f'ALTER TABLE {_q(table_id)} ADD COLUMN IF NOT EXISTS {_q(name)} {pg_type(uidt)}')

    def delete_table(self, table_id: str) -> None:
        with self._conn.cursor() as cur:
            cur.execute(f'DROP TABLE IF EXISTS {_q(table_id)}')

    # ── data ──────────────────────────────────────────────────────────────────
    def list_all(self, table_id: str, fields: list[str] | None = None,
                 page_size: int = 1000) -> list[dict]:
        cols = "*" if not fields else ", ".join(_q(f) for f in fields)
        with self._conn.cursor() as cur:
            cur.execute(f"SELECT {cols} FROM {_q(table_id)}")
            rows = cur.fetchall()
        return [{k: _coerce(v) for k, v in r.items()} for r in rows]

    def bulk_create(self, table_id: str, rows: list[dict]) -> int:
        return self._write_insert(table_id, rows)

    def bulk_update(self, table_id: str, rows: list[dict]) -> int:
        for r in rows:
            if "Id" not in r:
                raise NocoDBError("bulk_update row is missing 'Id'")
        return self._write_update(table_id, rows)

    def bulk_delete(self, table_id: str, ids: list[int]) -> int:
        if not ids:
            return 0
        with self._conn.cursor() as cur:
            cur.execute(f'DELETE FROM {_q(table_id)} WHERE {_q("Id")} = ANY(%s)',
                        ([int(i) for i in ids],))
        return len(ids)

    # group rows by their column set so a single executemany covers each group
    def _write_insert(self, table_id: str, rows: list[dict]) -> int:
        done = 0
        groups: dict[tuple, list[dict]] = {}
        for r in rows:
            groups.setdefault(tuple(sorted(r.keys())), []).append(r)
        with self._conn.cursor() as cur:
            for keys, group in groups.items():
                cols = list(keys)
                ph = ", ".join(["%s"] * len(cols))
                sql = (f'INSERT INTO {_q(table_id)} ({", ".join(_q(c) for c in cols)}) '
                       f"VALUES ({ph})")
                for i in range(0, len(group), CHUNK):
                    chunk = group[i:i + CHUNK]
                    cur.executemany(sql, [[g.get(c) for c in cols] for g in chunk])
                    done += len(chunk)
        return done

    def _write_update(self, table_id: str, rows: list[dict]) -> int:
        done = 0
        groups: dict[tuple, list[dict]] = {}
        for r in rows:
            data_cols = tuple(sorted(k for k in r.keys() if k != "Id"))
            groups.setdefault(data_cols, []).append(r)
        with self._conn.cursor() as cur:
            for cols, group in groups.items():
                if not cols:
                    continue
                setc = ", ".join(f"{_q(c)} = %s" for c in cols)
                sql = f'UPDATE {_q(table_id)} SET {setc} WHERE {_q("Id")} = %s'
                for i in range(0, len(group), CHUNK):
                    chunk = group[i:i + CHUNK]
                    cur.executemany(sql, [[g.get(c) for c in cols] + [g["Id"]] for g in chunk])
                    done += len(chunk)
        return done

    # ── post-migration: advance identity sequences past the copied max(Id) ──────
    def fix_identity(self, table_id: str) -> None:
        with self._conn.cursor() as cur:
            cur.execute(f'SELECT COALESCE(MAX({_q("Id")}),0) AS m FROM {_q(table_id)}')
            m = cur.fetchone()["m"] or 0
            cur.execute(
                "SELECT pg_get_serial_sequence(%s, 'Id') AS seq", ('"' + table_id + '"',))
            seq = cur.fetchone()["seq"]
            if seq:
                cur.execute("SELECT setval(%s, %s, true)", (seq, int(m) + 1))
